[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
ConvexHulls2d = "438b5665-92b0-42e6-bc36-e4ac8449fa2d"
Hypatia = "b99e6be6-89ff-11e8-14f8-45c827f4f8f2"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
